### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by RobinHung** [RobinHung/ubuntu-esm-scraper#1]
* [x] cli framework
* [ ] makefile
* [ ] tablewriter https://github.com/olekukonko/tablewriter
* [ ] colly: URL revisit optimization
* [x] output file format
